server:
  port: 8080
  servlet:
    context-path: /api

spring:
  application:
    name: user-center
# DataSource Config
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/project
    username: root
    password: cyw041127

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

files:
  uploads:
    path: C:\Users\czl\WebstormProjects\frontend\public\avatar\
